import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className="hidden lg:block">
            {children}
          </div>
          <div className="flex lg:hidden w-full h-screen items-center justify-center px-4">
            <h1 className="text-xl font-bold text-center">Please use desktop version for the best experience.</h1>
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
